name: workshop_management
description: "workshop_management"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  rxdart: ^0.27.0
  mobile_scanner: ^3.5.7
  flutter:
    sdk: flutter
  intl: ^0.18.0
  supabase_flutter: ^2.10.0
  image_picker: ^1.0.4
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.7.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
